### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by ahmedmahmood153**

### CODE REVIEW

**Comment by waldyrious** [comment]
Seems to be [Hacktoberfest spam](https://hacktoberfest.digitalocean.com/details#spam). 😞

**Comment by ahmedmahmood153** [comment]
> Seems to be [Hacktoberfest spam](https://hacktoberfest.digitalocean.com/details#spam). 😞

Yeah plz verify it

**Comment by mohouyizme** [comment]
@agarrharr 
image

**Comment by waldyrious** [comment]
@agarrharr you need to add the `invalid` or `spam` label for the PR to not be counted towards Hacktoberfest. (They have now c[hanged the mechanism to be opt-in](https://hacktoberfest.digitalocean.com/hacktoberfest-update), but PRs created before that are not subject to the new rules.)

**Pull request closed without merging**
